---
sudo: false
addons:
  apt:
    packages:
      - aspell
      - aspell-en
language: perl
perl:
  - 5.10.1
env:
  global:
    - RELEASE_TESTING=1
    - AUTHOR_TESTING=1
    - TRAVIS_PERL_DEBUG=1
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
